"""Huấn luyện MLP đa nhãn 15 -> 12 -> 8 -> 3 và xuất artifact tái lập."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import f1_score, hamming_loss, precision_score, recall_score, roc_auc_score
from sklearn.model_selection import GroupShuffleSplit
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler


LABELS = ["jam", "vibration", "sag"]


def load_columns(path: Path) -> list[str]:
    columns = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(columns, list) or len(columns) != 15:
        raise ValueError("feature_columns.json phải chứa đúng 15 tên cột")
    return [str(column) for column in columns]


def split_by_session(frame: pd.DataFrame, seed: int):
    if "session_id" not in frame or frame.session_id.nunique() < 2:
        raise ValueError("cần ít nhất hai session_id để chia train/test không rò rỉ")
    splitter = GroupShuffleSplit(n_splits=1, test_size=0.25, random_state=seed)
    train_index, test_index = next(splitter.split(frame, groups=frame.session_id))
    return frame.iloc[train_index], frame.iloc[test_index]


def metrics(y_true: np.ndarray, probability: np.ndarray) -> dict:
    prediction = (probability >= 0.5).astype(np.int8)
    result = {
        "micro_f1": float(f1_score(y_true, prediction, average="micro", zero_division=0)),
        "macro_f1": float(f1_score(y_true, prediction, average="macro", zero_division=0)),
        "micro_precision": float(precision_score(y_true, prediction, average="micro", zero_division=0)),
        "micro_recall": float(recall_score(y_true, prediction, average="micro", zero_division=0)),
        "hamming_loss": float(hamming_loss(y_true, prediction)),
        "labels": {},
    }
    for index, label in enumerate(LABELS):
        label_metrics = {
            "f1": float(f1_score(y_true[:, index], prediction[:, index], zero_division=0)),
            "positive_samples": int(y_true[:, index].sum()),
        }
        if np.unique(y_true[:, index]).size == 2:
            label_metrics["roc_auc"] = float(roc_auc_score(y_true[:, index], probability[:, index]))
        result["labels"][label] = label_metrics
    return result


def c_array(name: str, values: np.ndarray) -> str:
    array = np.asarray(values)
    dimensions = "".join(f"[{size}]" for size in array.shape)
    if array.ndim == 1:
        body = ", ".join(f"{value:.9e}f" for value in array)
        return f"static const float {name}{dimensions} = {{{body}}};"
    rows = ["  {" + ", ".join(f"{value:.9e}f" for value in row) + "}" for row in array]
    return f"static const float {name}{dimensions} = {{\n" + ",\n".join(rows) + "\n};"


def export_header(pipeline: Pipeline, golden_x: np.ndarray, path: Path) -> None:
    scaler: StandardScaler = pipeline.named_steps["scaler"]
    model: MLPClassifier = pipeline.named_steps["model"]
    golden_frame = pd.DataFrame([golden_x], columns=pipeline.feature_names_in_)
    golden_y = pipeline.predict_proba(golden_frame)[0]
    lines = [
        "#pragma once",
        "// Auto-generated by huan_luyen_mo_hinh.py. Labels: jam, vibration, sag.",
        "static const int MC_INPUTS = 15;",
        "static const int MC_H1 = 12;",
        "static const int MC_H2 = 8;",
        "static const int MC_OUTPUTS = 3;",
        c_array("MC_MEAN", scaler.mean_),
        c_array("MC_SCALE", scaler.scale_),
        c_array("MC_W0", model.coefs_[0]), c_array("MC_B0", model.intercepts_[0]),
        c_array("MC_W1", model.coefs_[1]), c_array("MC_B1", model.intercepts_[1]),
        c_array("MC_W2", model.coefs_[2]), c_array("MC_B2", model.intercepts_[2]),
        c_array("MC_TEST_X", golden_x), c_array("MC_TEST_Y", golden_y),
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("features_csv", type=Path)
    parser.add_argument("--columns", type=Path, default=Path(__file__).parents[1] / "du_lieu/feature_columns.json")
    parser.add_argument("--out", type=Path, default=Path(__file__).parents[1] / "mo_hinh")
    parser.add_argument("--firmware-header", type=Path)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    frame = pd.read_csv(args.features_csv)
    feature_columns = load_columns(args.columns)
    required = [*feature_columns, *LABELS, "session_id"]
    missing = [column for column in required if column not in frame]
    if missing:
        raise ValueError(f"CSV thiếu cột: {', '.join(missing)}")
    if not np.isfinite(frame[feature_columns].to_numpy(dtype=float)).all():
        raise ValueError("dữ liệu huấn luyện có NaN hoặc vô cực")

    train, test = split_by_session(frame, args.seed)
    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("model", MLPClassifier(
            hidden_layer_sizes=(12, 8), activation="relu", solver="adam",
            max_iter=1000, early_stopping=True, validation_fraction=0.2,
            random_state=args.seed,
        )),
    ])
    pipeline.fit(train[feature_columns], train[LABELS].astype(int))
    probability = np.asarray(pipeline.predict_proba(test[feature_columns]), dtype=float)
    report = {
        "seed": args.seed,
        "features": feature_columns,
        "labels": LABELS,
        "train_rows": len(train), "test_rows": len(test),
        "train_sessions": sorted(train.session_id.astype(str).unique().tolist()),
        "test_sessions": sorted(test.session_id.astype(str).unique().tolist()),
        "metrics": metrics(test[LABELS].to_numpy(dtype=int), probability),
    }

    args.out.mkdir(parents=True, exist_ok=True)
    joblib.dump(pipeline, args.out / "motorcare_mlp.joblib")
    (args.out / "metadata.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8",
    )
    if args.firmware_header:
        export_header(pipeline, test[feature_columns].iloc[0].to_numpy(dtype=float), args.firmware_header)
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
